config/routes.rb
Rails.application.routes.draw do
      root to: "products#top"
   get '/about',to: 'products#about'
  
  get '/search/genre', to: 'products#search_genre'
  devise_for :admins, controllers: {
      sessions:      'admins/sessions',
      passwords:     'admins/passwords',
      registrations: 'admins/registrations'
  }
  devise_for :customers, controllers: {
      sessions:      'customers/sessions',
      passwords:     'customers/passwords',
      registrations: 'customers/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routiSZng.html

  namespace :admins do
    resources :orders, only: [:index,:show,:update]
    get '/top', to: "orders#top"
    resources :customers
    resources :products
    resources :genres, only: [:index ,:create, :edit, :update]
    get 'product/top',to: "products#top"

  end
  namespace :customers do
    get '/thanks', to: 'orders#thanks'
    resources :carts, only: [:index ,:create, :update, :destroy]
    delete '/all_carts_destroy', to: "carts#all_destroy", as: "all_destroy"
    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        post :new,path: :new, as: :new
        post :about
      end
    end
  end
  resources :products

    get '/customer/cancel', to: 'customers#cancel'
    get '/customers', to: 'customers#show'
    get '/customers/pass', to: 'customers#pass'
    resources :customers do
      patch :customer_status
      resources :deliveries, only:[:index, :edit, :update, :destroy, :new, :create]
  end
  devise_scope :customer do
    get '/customers/sign_out' => 'devise/sessions#destroy'
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
	devise :database_authenticatable, :registerable,
			:recoverable, :rememberable, :validatable
    has_many :carts
    has_many :orders
    enum customer_status: {有効: 0, 無効: 1 }
  	has_many :deliveries
	validates :lastname, presence: true
	validates :firstname, presence: true
	validates :lastkana, presence: true
	validates :firstkana, presence: true
	validates :email, presence: true
	validates :telephone_number, presence: true
	validates :postal_code, presence: true
	validates :address, presence: true
	validates :customer_status, inclusion: { in: Customer.customer_statuses.keys }
	def self.find_for_authentication(conditions)
		super(conditions.merge(:customer_status => "有効"))
	end
	# def inactive_message
	# 無効? super: :invaild_status
 #    end
	def customer_status!
      if 有効?
         無効!
      else
        無効!
      end
    end
 #    def active_for_authentication?
 #    super && 有効?
 #    end
    def inactive_message
	無効? super :invaild_status
    end
	# allow customers to update their accounts without passwords
end

app/models/order.rb
class Order < ApplicationRecord
	has_many :order_details
	accepts_nested_attributes_for :order_details
	belongs_to :customer
	enum order_status:{
	入金待ち: 0, 入金確認: 1, made: 2, 発送準備中: 3, 発送済み: 4
	}
	enum payment_method:{
	クレジットカード: 0, 現金振込: 1
	}
end

app/controllers/admins/customers_controller.rb
class Admins::CustomersController < ApplicationController

	def index
		@customers = Customer.all
    end
	def show
		@customer = Customer.find(params[:id])
	end
	def edit
		@customer = Customer.find(params[:id])
	end
	def update
		@customer = Customer.find(params[:id].to_i)
		@customer.update(customer_params)
    redirect_to admins_customers_path
	end
	def top
		@customer = Customer.find(params[:id])
	end

	def customer_params
  	params.require(:customer).permit(:lastname, :firstname, :lastkana, :firstkana, :telephone_number, :postal_code, :address, :email, :customer_status)
  end
end

app/controllers/admins/orders_controller.rb
class Admins::OrdersController < ApplicationController
	def index
		@orders = Order.all
	end
	def update
		@order = Order.find(params[:id])
		@order_details = @order.order_details
        # @order.update(order_params)
        @order.update(order_status: params[:order][:order_status].to_i)
	        if @order_details.where(production_status: 2).any?
	        	  @order.update(order_status: 2)
	        else
	        end
	        if @order.order_status_before_type_cast == 1
	        	@order_details.each do |item|
	           		item.update(production_status: 1)
	       		end
	        end
	        if @order_details.count == @order_details.where(production_status: 3).count
	        	  @order.update(order_status: 3)
	        else
	        end

        redirect_to admins_order_path
	end
	def show
		@order = Order.find(params[:id])
	end
	def top
		from = Time.current.beginning_of_day
		to = Time.current.end_of_day
		@count = Order.where(created_at: from..to).count

	end
	def order_params
		params.permit(:deliver_to, :shipping_name, :order_postshipping_cost, :order_status, :payment_method, :created_at, order_detail_attributes: [:id, :production_status])
	end
	def order_detail_params
		params.require(:order_detail).permit(:ordered_price, :ordered_item_name, :ordered_item_count, :production_status)
	end
end

app/controllers/customers/carts_controller.rb
class Customers::CartsController < ApplicationController
  def index
    @carts = current_customer.carts
    @customer = current_customer
    @tax = Tax.find(2).tax
  end

  def create
    @addcart = Cart.new(cart_params)
    @addcart.customer_id = current_customer.id
    @addcart.save
    redirect_to customers_carts_path

    # binding.pry
    # p "hhhhhh"
    # @addcart = add_cart(params[:cart][:item_count],params[:cart][:product_id])
    # @addcart.save
    # redirect_to customers_carts_path
  end

  def add_cart(item_count,product_id)
    # ジャッジさせたcart_existを元に
    # frueなら個数のみ追加登録（＋）
    if cart_exist(params[:cart][:product_id])
      cart = Cart.new
      cart.customer_id = current_customer.id
      cart.product_id = product_id
      cart.item_count = item_count
    # falseなら空のカラムを渡して新しくカートへ登録
    else
      cart = Cart.find_by(product_id:product_id)
      cart.item_count += item_count
    end
    return cart
  end

    # 現在のカート内に登録しようとしているproduct_idがないかジャッジさせる
  def cart_exist(product_id)
    @carts = Cart.where(customer_id:current_customer.id)
    @carts.each do |p|
      if product_id == p.product_id
        return true
      else
        return false
      end
    end
  end

 # m=Memo.find(1)探して見つけて呼び出して
 # m.body="aaaaaaaaaaaaaaaaa"個数を追加してクリエイトして
 # m.saveセーブする


  def update
    @cart = Cart.find(params[:id])
    @cart.update(cart_params)
    redirect_to customers_carts_path
  end

  def destroy
    @cart = Cart.find(params[:id])
    @cart.destroy
    redirect_to customers_carts_path
  end

  def all_destroy
    @carts = current_customer.carts
    @carts.delete_all
    redirect_to customers_carts_path
  end

  def cart_params
    params.require(:cart).permit(:item_count, :customer_id, :product_id)
  end
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/orders_controller.rb
class Customers::OrdersController < ApplicationController
	# before_action :order_params
	def index
		@orders = current_customer.orders.includes(:order_details)
	end
	def show
		@order = Order.find(params[:id])
	end
	def about
		@customer = current_customer
		@order = @customer.orders.new
		@carts = current_customer.carts
	    @tax = Tax.find(2).tax
	    @products = Product.all
	    @total_price = 0
	    @carts.each do |cart|
     	@total_price += cart.product.non_tax * cart.item_count * 1.1
     	end
		if params[:post] == "post_mine_group"
			@order.order_post = @customer.postal_code
			@order.deliver_to = @customer.address
			@order.shipping_name = @customer.lastname + @customer.firstname
		elsif params[:post] == "post_deli_group"
			delivery = Delivery.find(params[:registered_address_id].to_i)
  			@order.order_post = delivery.delivery_post
			@order.deliver_to = delivery.delivery_address
			@order.shipping_name = delivery.delivery_name
	  	elsif
	  		params[:post] == "post_new_group"
	  		@order.order_post = params[:order_post]
	  		@order.deliver_to = params[:deliver_to]
	  		@order.shipping_name = params[:shipping_name]
		end
    end
	def thanks
		@customer = current_customer
	end
	def new
		@customer = current_customer
		@deliveries = current_customer.deliveries
	end
	def create
        @order = current_customer.orders.new(order_params)
		if @order.save
		   current_customer.carts.each do |cart|
				@order_detail = OrderDetail.new
				@order_detail.order_id = @order.id
				@order_detail.ordered_item_name = cart.product.product_name
				@order_detail.ordered_price = params[:ordered_price]
				@order_detail.ordered_item_count = cart.item_count
				@order_detail.save
				current_customer.carts.delete_all
		   end
		    redirect_to customers_thanks_path
   		else
      		render :new
    	end
	end


private

	def order_params
		params.permit(:deliver_to, :shipping_name, :order_post)
	end
	def order_detail_params
		params.require(:order_detail).permit(:ordered_price, :ordered_item_name)
	end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
     # before_action :set_customer, only: [:show, :destroy, :customer_status]
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
    def update
    @customer = current_customer
    @customer.update(customer_params)
        redirect_to controller: :customers, action: :show
    end
    def cancel
    @customer = current_customer
    end
  #   def customer_status
  #   @customer.customer_status!
  #   redirect_to @customer, notice: 'successfully updated.'
  # end

  # private
    # Use callbacks to share common setup or constraints between actions.
    # def set_customer
      # @customer = Customer.find(params[:id].to_i || params[:customer_id])
    # end
    # def customer_params
    # params.require(:customer).permit(:lastname, :firstname, :lastkana, :firstkana, :telephone_number, :postal_code, :address, :email)
    # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
	  before_action :set_customer, only: [:show, :edit, :update, :destroy, :customer_status]
	def show
		@customer = current_customer
	end
	def edit
		@customer = Customer.find(params[:id].to_i)
	end
	def cancel
		@customer = Customer.find(params[:id].to_i)
	end
	def update
		@customer = Customer.find(params[:id].to_i)
		@customer.update(customer_params)
        redirect_to customers_path
    end
    def pass
		@customer = current_customer
    end
    def customer_status
    @customer.customer_status!
    redirect_to destroy_customer_session_path, method: :delete
  	end
    def customer_params
  	params.require(:customer).permit(:lastname, :firstname, :lastkana, :firstkana, :telephone_number, :postal_code, :address, :email, :customer_status)
    end
    private
    def set_customer
      @customer = current_customer ||  Customer.find(params[:id])
    end
end

app/helpers/admins/customers_helper.rb
module Admins::CustomersHelper
end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/helpers/customers/cart_helper.rb
module Customers::CartHelper
end

app/helpers/customers/customers_helper.rb
module Customers::CustomersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/customers/orders/about.html.erb
<body>

<%= render 'headfoot/header' %>
<div class="container">
	<div class="row">
		<% @carts.each do |cart| %>
		<table class="table-border">
			<tr>
				<th class="col-xs-4">商品名</th>
				<th class="col-xs-1">単価（税込）</th>
				<th class="col-xs-1">数量</th>
				<th class="col-xs-1">小計</th>
			</tr>

			<tr>
				<td>
					<%= attachment_image_tag @product, :product_image, :fill, 50, 50, fallback:"No-Image-Available.png",size: :"50x50" %>
              		<%= cart.product.product_name %>
				</td>
				<td>
            		<%= (cart.product.non_tax * @tax).floor %>
				</td>
				<td>
					<%= cart.item_count %>
				</td>
				<td>
					<%= (cart.product.non_tax * @tax * cart.item_count).floor %>
				</td>
			</tr>
		</table>
		<% end %>
		<table>
			<tr>
				<th>送料</th>
				<td><%= @order.shipping_cost %></td>
			</tr>
			<tr>
				<th>商品合計</th>
				<td>
					<% sum = 0 %>
		            <% @carts.each do |cart| %>
		            <% sub_total = (cart.product.non_tax * @tax * cart.item_count).floor %>
		            <% sum += sub_total %>
		            <% end %>
		            <%= sum %>
				</td>
			</tr>
			<tr>
				<th>請求金額</th>
				<td><%= sum + @order.shipping_cost %></td>
			</tr>
		</table>
	</div>
	<div class="row">
		<h3>支払方法</h3>
		<%= @order.payment_method %>
	</div>
	<div class="row">
		<h3>お届け先</h3>
		<div>
		  〒<%= @order.order_post %>
	    <%= @order.deliver_to %>
		  <%= @order.shipping_name %>
			<%= form_tag(customers_orders_path, method: :post) do %>
		    <%= hidden_field_tag :payment_method  %>
				<%= hidden_field_tag :order_post, @order.order_post   %>
				<%= hidden_field_tag :deliver_to, @order.deliver_to %>
				<%= hidden_field_tag :shipping_name, @order.shipping_name %>
				<%= hidden_field_tag :ordered_price, @total_price %>
				<% @carts.each do |cart| %>
					<%= hidden_field_tag :ordered_item_count, cart.item_count %>
				<% end %>
				<%= submit_tag("注文を確定する", class: "btn btn-primary") %>
			<% end %>
		</div>
	</div>
</div>
<%= render 'headfoot/footer' %>

</body>

app/views/customers/orders/index.html.erb
<body>

<%= render 'headfoot/header' %>
<div class="container">
	<div class="row">
		<h3>注文履歴一覧</h3>
	</div>
	<div class="row">
		<table class="col-xs-12 table-bordered">
			<tr>
				<th class="col-xs-1">注文日</th>
				<th class="col-xs-4">配送先</th>
				<th class="col-xs-2">注文商品</th>
				<th class="col-xs-1">支払金額</th>
				<th class="col-xs-1">ステータス</th>
				<th class="col-xs-1">注文詳細</th>
			</tr>
			<% @orders.each do |order| %>
			<tr>
				<td>
					<%= order.created_at.strftime('%Y/%m/%d') %>
				</td>
				<td>
					<%= order.order_post %><br>
					<%= order.deliver_to %><br>
					<%= order.shipping_name %>
				</td>
				<td>
					<% order.order_details.each do |detail| %>
					<%= detail.ordered_item_name %>
					<% end %>
				</td>
				<td>
					<% sum = 0 %>
					<% order.order_details.each do |detail| %>
		            <% sum += detail.ordered_price.to_i %>
		            <% end %>
		            <%= sum + order.shipping_cost.to_i  %>
				</td>
				<td>
					<%= order.order_status %>
				</td>
				<td class="edit-btn">
					<%= link_to "表示する",  customers_order_path(order), class: "btn btn-primary" %>
				</td>
			</tr>
			<% end %>
		</table>
	</div>
</div>
<%= render 'headfoot/footer' %>

</body>

app/views/customers/orders/new.html.erb
<body>

<%= render 'headfoot/header' %>
<div class="container">
	<h3>購入情報入力</h3>
	<div class="row">
		<h3>支払方法</h3>
		<%= form_tag(about_customers_orders_path, method: :post)  do %>
		<label><%= radio_button_tag(:payment_method, :クレジットカード, true ) %>　クレジットカード</label><br>
		<label><%= radio_button_tag(:payment_method, :現金振込) %>　現金振込</label>
	</div>

		<h3>お届け先</h3>

	<div class="row" style="padding-bottom: 30px;">
    	<label>
    		<%= radio_button_tag(:post, "post_mine_group", true) %>
    		<!-- <input type="radio" id ="post1" name="post" value= "post_mine_group" >　 -->ご自身の住所
    	</label>
    			<%= hidden_field_tag :customer_address, @customer.address %>
    			<%= hidden_field_tag :customer_postal_code, @customer.postal_code %>
    			<%= hidden_field_tag :customer_name, @customer.lastname %>
    			<%= hidden_field_tag :customer_name, @customer.firstname %>
		      　〒<%= @customer.postal_code %>
		    	<%= @customer.address %>
		    	<%= @customer.lastname %><%= @customer.firstname %>
	</div>

	<div class="row" style="padding-bottom: 30px;">
	    <label>
	    	<%= radio_button_tag(:post, "post_deli_group") %>
	    	<!-- <input type="radio" id ="post2" name="post" value ="post_deli_group" > -->　登録済住所から選択
	    </label>
	    	<br>
			<%= select_tag :registered_address_id, options_for_select(@deliveries.collect { |d| ["〒#{d.delivery_post} #{d.delivery_address} #{d.delivery_name}", d.id] }) %>

	</div>

	<div class="row" style="padding-bottom: 30px;">
		<label>
			<%= radio_button_tag(:post, "post_new_group") %>
			<!-- <input type="radio" id="post3" name="post" value="post_new_group" > -->　新しいお届け先
		</label>
		<table>
	        <tr>
	          <th class="col-xs-2">郵便番号</th>
	            <td style="padding: 10px;">
	            <%= text_field_tag :order_post, "", {placeholder: :"123-4567", class: "post_new"} %>
	            </td>
	        </tr>
	        <tr>
	          <th class="col-xs-2">住所</th>
	            <td style="padding: 10px;">
	              <%= text_field_tag :deliver_to, "", {placeholder: :"東京都", class: "post_new", style: "width: 100%;"} %>
	            </td>
	        </tr>
	        <tr>
	          <th class="col-xs-2">宛名</th>
	            <td style="padding: 10px;">
	              <%= text_field_tag :shipping_name, "", {placeholder: :"渋谷", class: "post_new", style: "width: 100%;"}  %>
	            </td>
	        </tr>
	    </table>
	    <div style = "padding-top: 30px;">
	    <%= submit_tag("確認画面へ進む", class: "btn btn-primary") %>
	    </div>
	    <% end %>
	</div>
</div>

<%= render 'headfoot/footer' %>

</body>

app/views/customers/orders/show.html.erb
<body>

<%= render 'headfoot/header' %>
<div class="container">
	<h3>注文履歴詳細</h3>
	<!-- 注文情報テーブル -->
	<div class="row col-lg-12">
		<div class="col-xs-5">
			<h4>注文情報</h4>
			<table class="table-bordered">
				<tr class="order-show">
					<th class="col-xs-2">注文日</th>
					<td class="col-xs-4"><%= @order.created_at.strftime('%Y/%m/%d') %></td>
				</tr>
				<tr class="order-show">
					<th class="col-xs-2">配送先</th>
					<td class="col-xs-4">
						<%= @order.order_post %><br>
						<%= @order.deliver_to %><br>
						<%= @order.shipping_name %>
					</td>
				</tr>
				<tr class="order-show">
					<th class="col-xs-2">支払方法</th>
					<td class="col-xs-4">
						<%= @order.payment_method %>
					</td>
				</tr>
				<tr class="order-show">
					<th class="col-xs-2">ステータス</th>
					<td class="col-xs-4"><%= @order.order_status %></td>
				</tr>
			</table>
		</div>
		<!-- 請求情報 -->
		<div>
			<table class="table-bordered pay-table col-xs-5">
				<h4>請求情報</h4>
				<tr class="order-show">
					<th class="col-xs-2">商品合計</th>
					<td class="col-xs-2">
						<% sum = 0 %>
			            <% @order.order_details.each do |order| %>
			            <% sub_total = order.ordered_price.to_i * order.ordered_item_count.to_i %>
			            <% sum += sub_total %>
			            <% end %>
			            <%= sum %>
					</td>
				</tr>
				<tr class="order-show">
					<th class="col-xs-2">配送料</th>
					<td class="col-xs-2">
						<%= @order.shipping_cost %>
					</td>
				</tr>
				<tr class="order-show">
					<th class="col-xs-2">ご請求額</th>
					<td class="col-xs-2">
			            <% @order.order_details.each do |order| %>
			            <% order.ordered_price.to_i * order.ordered_item_count.to_i %>
			            <% end %>
			            <% sum %>
						<%= sum + @order.shipping_cost %>
					</td>
				</tr>
			</table>
		</div>
	</div>
	<!-- 注文内容 -->
		<h4 class="col-lg-12">注文内容</h4>
	<div class="row　col-lg-12 order-item">
		<div class="col-lg-9">
			<table class="table-bordered col-xs-8 ">
					<tr class="order-show">
						<th>商品</th>
						<th>単価（税込）</th>
						<th>個数</th>
						<th>小計</th>
					</tr>
					<% @order.order_details.each do |order| %>
					<tr class="order-show">
						<td class="col-xs-2">
							<%= order.ordered_item_name %>
						</td>
						<td class="col-xs-1">
							<%= order.ordered_price %>
						</td>
						<td class="col-xs-1">
							<%= order.ordered_item_count %>
						</td>
						<td class="col-xs-1">
							<%= order.ordered_item_count.to_i * order.ordered_price.to_i %>
						</td>
					</tr>
					<% end %>
			</table>
		</div>
	</div>
</div>
<%= render 'headfoot/footer' %>

</body>

app/views/customers/orders/thanks.html.erb
<body>

<%= render 'headfoot/header' %>
<div class="container">
	<div class="row col-xs-12" style="text-align: center;">
		<h2>ご購入ありがとうございました</h2>
	</div>
</div>
<%= render 'headfoot/footer' %>

</body>