config/routes.rb
Rails.application.routes.draw do
      root to: "products#top"
   get '/about',to: 'products#about'
  
  get '/search/genre', to: 'products#search_genre'
  devise_for :admins, controllers: {
      sessions:      'admins/sessions',
      passwords:     'admins/passwords',
      registrations: 'admins/registrations'
  }
  devise_for :customers, controllers: {
      sessions:      'customers/sessions',
      passwords:     'customers/passwords',
      registrations: 'customers/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routiSZng.html

  namespace :admins do
    resources :orders, only: [:index,:show,:update]
    get '/top', to: "orders#top"
    resources :customers
    resources :products
    resources :genres, only: [:index ,:create, :edit, :update]
    get 'product/top',to: "products#top"

  end
  namespace :customers do
    get '/thanks', to: 'orders#thanks'
    resources :carts, only: [:index ,:create, :update, :destroy]
    delete '/all_carts_destroy', to: "carts#all_destroy", as: "all_destroy"
    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        post :new,path: :new, as: :new
        post :about
      end
    end
  end
  resources :products

    get '/customer/cancel', to: 'customers#cancel'
    get '/customers', to: 'customers#show'
    get '/customers/pass', to: 'customers#pass'
    resources :customers do
      patch :customer_status
      resources :deliveries, only:[:index, :edit, :update, :destroy, :new, :create]
  end
  devise_scope :customer do
    get '/customers/sign_out' => 'devise/sessions#destroy'
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
 has_many :products
  enum genre_status: {
    有効: 0, 無効: 1
  }
end

app/controllers/admins/genres_controller.rb
class Admins::GenresController < ApplicationController
  def index
    @genres = Genre.all
    @newgenre = Genre.new
  end

  def create
    @newgenre = Genre.new(genre_params)
    @newgenre.save
    redirect_to admins_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admins_genres_path
  end

  private
  def genre_params
    params.require(:genre).permit(:genre_name, :genre_status)
  end
end

app/views/admins/genres/edit.html.erb
<body>

<%= render 'headfoot/header' %>

<h1>ジャンル　編集画面・更新</h1>

<%= form_for(@genre, url: admins_genre_path) do |f| %>

  <p>ジャンル作成</p>
  <%= f.text_field :genre_name %>

  <%= f.radio_button :genre_status, :有効 %>
  <%= f.label :genre_status, "有効" %>
  <%= f.radio_button :genre_status, :無効 %>
  <%= f.label :genre_status, "無効" %>

  <br><%= f.submit 'Update Genre' %></br>
<% end %>

<%= render 'headfoot/footer' %>

</body>

app/views/admins/genres/index.html.erb
<body>

<%= render 'headfoot/header' %>

<div class="container">
  <h1>ジャンル　一覧・新規作成・編集遷移</h1>

  <h2>ジャンル新規作成</h2>
  <%= form_for(@newgenre, url: admins_genres_path) do |f| %>

    <p>ジャンル作成</p>
    <%= f.text_field :genre_name %>

    <%= f.radio_button :genre_status, :有効 %>
    <%= f.label :genre_status, "有効" %>
    <%= f.radio_button :genre_status, :無効 %>
    <%= f.label :genre_status, "無効" %>

    <br><%= f.submit 'Create Genre' %></br>
  <% end %>

  <h2>ジャンル一覧</h2>

  <table class="table">
    <tbody>
      <% @genres.each do |genre| %>
        <tr>
          <td></td>
          <td>
            <%= genre.genre_name %>
          </td>
          <td>
            <%= genre.genre_status %>
          </td>
          <td>
            <%= link_to "編集する", edit_admins_genre_path(genre) %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= render 'headfoot/footer' %>

</body>