config/routes.rb
Rails.application.routes.draw do
      root to: "products#top"
   get '/about',to: 'products#about'
  
  get '/search/genre', to: 'products#search_genre'
  devise_for :admins, controllers: {
      sessions:      'admins/sessions',
      passwords:     'admins/passwords',
      registrations: 'admins/registrations'
  }
  devise_for :customers, controllers: {
      sessions:      'customers/sessions',
      passwords:     'customers/passwords',
      registrations: 'customers/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routiSZng.html

  namespace :admins do
    resources :orders, only: [:index,:show,:update]
    get '/top', to: "orders#top"
    resources :customers
    resources :products
    resources :genres, only: [:index ,:create, :edit, :update]
    get 'product/top',to: "products#top"

  end
  namespace :customers do
    get '/thanks', to: 'orders#thanks'
    resources :carts, only: [:index ,:create, :update, :destroy]
    delete '/all_carts_destroy', to: "carts#all_destroy", as: "all_destroy"
    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        post :new,path: :new, as: :new
        post :about
      end
    end
  end
  resources :products

    get '/customer/cancel', to: 'customers#cancel'
    get '/customers', to: 'customers#show'
    get '/customers/pass', to: 'customers#pass'
    resources :customers do
      patch :customer_status
      resources :deliveries, only:[:index, :edit, :update, :destroy, :new, :create]
  end
  devise_scope :customer do
    get '/customers/sign_out' => 'devise/sessions#destroy'
  end

end

app/models/product.rb
class Product < ApplicationRecord
    has_many :carts
	belongs_to :genre
 	attachment :product_image
	enum product_status: {
		販売中: 0, 販売停止中: 1
	}

  def self.search(search)
    if search
      Product.where(['product_name LIKE ?', "%#{search}%"])
    else
      Product.all
    end
  end
end

app/controllers/admins/products_controller.rb
class Admins::ProductsController < ApplicationController
 # あとでbefore_action :authenticate_user!を追加
  def index
    @product_all = Product.search(params[:search])

  end

  def show
    @product = Product.find(params[:id])
    @genre = @product.genre.genre_name
  end

  def new
    @product_new = Product.new
    @genre = Genre.all
  end

  def create
    @product = Product.new(products_params)
    if @product.save
      redirect_to admins_product_path(@product.id)
    else
      redirect_to admims_product_path
    end

  end

  def edit
    @product = Product.find(params[:id])
    @genre = Genre.all
  end

  def update
    product = Product.find(params[:id])
    if product.update(products_params)
      redirect_to admins_product_path
    else
      redirect_to admins_products_path
    end
  end


  def top
      # range = Date.today.beginning_of_day..Date.today.end_of_day
      # @count = Order.where(created_at: range)
  end


private
  def products_params
      params.require(:product).permit(:product_name, :non_tax, :product_image, :product_description, :product_status, :genre_id)
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_customer!, { except: [:top, :about, :index, :show, :search_genre] }
  def top
    @products = Product.all.page(params[:page]).reverse_order
    @tax = Tax.find(2).tax
  end

  def about
  end

  def index
    @products = Product.search(params[:search])
    @genres = Genre.all
    @product_onsale = Product.where(product_status: 0).all.page(params[:page]).reverse_order
    @tax = Tax.find(2).tax
  end

  def search_genre
    @genres = Genre.all
    @product_onsale = Product.where(genre_id: params[:id].to_i).page(params[:page]).reverse_order
    @tax = Tax.find(2).tax
    render :index
  end

  def show
  	@product = Product.find(params[:id])
    @addcart = Cart.new

    @tax = Tax.find(2).tax
  end


  def product_params
    params.require(:product).permit(:genre_id, :product_name, :non_tax, :product_image_id, :product_description, :product_status)
  end
end

app/helpers/admins/products_helper.rb
module Admins::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/about.html.erb

<body>

<%= render 'headfoot/header' %>

<div id="headerwrap" name="home" class="fullheight">
<header class="clearfix fullheight">
  <div id="container" class="vertical-center">
    <div id="xx">
      <div class="image1">
        <p class="animated slideInLeft">
          Welcome to Nagano Cake.
        </p>
        <p class="animated slideInRight">Well then, let's begin.</p>
        <%= link_to "Sign in", new_customer_registration_path, data: {"turbolinks" => false}, class: 'btn homebtn smoothScroll anime_test' %>
        <i class="el-icon-chevron-down homeicon"></i>
      </div>
      <div class="image2">
        <p class="animated slideInLeft">
          Welcome to Nagano Cake.
        </p>
        <p class="animated slideInRight">Well then, let's begin.</p>
        <%= link_to "Sign in", new_customer_registration_path, data: {"turbolinks" => false}, class: 'btn homebtn smoothScroll anime_test' %>
        <i class="el-icon-chevron-down homeicon"></i>
      </div>
      <div class="image3">
        <p class="animated slideInLeft">
          Welcome to Nagano Cake.
        </p>
        <p class="animated slideInRight">Well then, let's begin.</p>
        <%= link_to "Sign in", new_customer_registration_path, data: {"turbolinks" => false}, class: 'btn homebtn smoothScroll anime_test' %>
        <i class="el-icon-chevron-down homeicon"></i>
      </div>
      <div class="image4">
        <p class="animated slideInLeft">
          Welcome to Nagano Cake.
        </p>
        <p class="animated slideInRight">Well then, let's begin.</p>
        <%= link_to "Sign in", new_customer_registration_path, data: {"turbolinks" => false}, class: 'btn homebtn smoothScroll anime_test' %>
        <i class="el-icon-chevron-down homeicon"></i>
      </div>
      <div class="image5">
        <p class="animated slideInLeft">
          Welcome to Nagano Cake.
        </p>
        <p class="animated slideInRight">Well then, let's begin.</p>
        <%= link_to "Sign in", new_customer_registration_path, data: {"turbolinks" => false}, class: 'btn homebtn smoothScroll anime_test' %>
        <i class="el-icon-chevron-down homeicon"></i>
      </div>
    </div>
  </div>

  </div>
  </header>
</div>


<%= render 'headfoot/footer' %>

</body>

app/views/products/index.html.erb
<body>

<div id="head-pic">
  <div id="theTarget">
    <div class="image1"></div>
    <div class="image2"></div>
    <div class="image3"></div>
    <div class="image4"></div>
    <div class="image5"></div>
  </div>
</div>

<%= render 'headfoot/header' %>
<%= render 'headfoot/sidebar' %>

<body>
  <div>
    <%= form_tag products_path, :method => 'get' do %>
      <%= label_tag :product_name, "気になる商品名" %>
      <%= text_field_tag :search, params[:search], :placeholder => "部分一致検査" %>
      <%= submit_tag "検索する", :product_name => nil %>
    <% end %>
    <%= yield %>
  </div>

  <div class="container indexitems">
    <div class="row">
      <div class="col-sm-9">
        <% @product_onsale.each do |product| %>
          <div class="indexeachitems">
            <%= link_to product_path(product.id) do %>
              <%= attachment_image_tag product, :product_image, :fill, 250, 250, fallback:"No-Image-Available.png",size: :"250x250" %>
            <% end %>
            <p class="product_name"><%= product.product_name %></p>
            <p class="product_price"><%= (product.non_tax * @tax).floor %>円</p>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-sm-3"></div>
 <%= paginate @product_onsale, class: "paginate" %>
</body>

<%= render 'headfoot/footer' %>

</body>

app/views/products/show.html.erb
<body>

<div id="head-pic">
   <div id="theTarget">
    <div class="image1"></div>
    <div class="image2"></div>
    <div class="image3"></div>
    <div class="image4"></div>
    <div class="image5"></div>
   </div>
 </div>

<%= render 'headfoot/header' %>
<%= render 'headfoot/sidebar' %>

<body>

<div class="container itemdetails">
	<div class="row">
		<div class="col-xs-3">
 <td><%= attachment_image_tag @product, :product_image, :fill, 400, 300, fallback:"No-Image-Available.png",size: :"400x300" %></td>
     </div>
   <div class="description col-xs-9">
       <p class="itemname"><%= @product.product_name %></p>
       <p class="itemdescription"><%= @product.product_description %></p>

        <p class="itemprice">価格（税込み）<%= (@product.non_tax * @tax).floor %>円</p>
    </div>
</div>
  <div class="row">
    <%= form_for @addcart, url: customers_carts_path do |f| %>
      <%= f.select :item_count, ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], {include_blank: '選択ボックス'} %>
      <%= f.hidden_field :product_id, :value => @product.id %>
      <%= f.submit  'カートに追加' %>
    <% end %>
  </div>
</div>
</body>
<%= render 'headfoot/footer' %>

</body>

app/views/products/top.html.erb
<%= render 'headfoot/header' %>

<div id="head-pic">
	<div id="theTarget">
		<div class="image1"></div>
		<div class="image2"></div>
		<div class="image3"></div>
		<div class="image4"></div>
		<div class="image5"></div>
	</div>
</div>


<body>
	<div class="container topitem">
		<div class="row">
			<div class="col-sm-2"></div>

  			 <div class="col-sm-8">
			  <% @products.each do |product| %>
				<div class="topindex">
					<%= link_to product_path(product.id) do %>
					<%= attachment_image_tag product, :product_image, :fill, 250, 250, fallback:"No-Image-Available.png",size: :"250x250" %>
					<% end %>
					<p class="product_name"><%= product.product_name %></p>
					<p class="product_price"><%= (product.non_tax * @tax).floor %>円</p>

				 	</div>
				<% end %>
			</div>
			<div class="col-sm-2">
		</div>
	</div>
</body>
<%= paginate @products, class: "paginate" %>
<%= render 'headfoot/footer' %>