config/routes.rb
Rails.application.routes.draw do
      root to: "products#top"
   get '/about',to: 'products#about'
  
  get '/search/genre', to: 'products#search_genre'
  devise_for :admins, controllers: {
      sessions:      'admins/sessions',
      passwords:     'admins/passwords',
      registrations: 'admins/registrations'
  }
  devise_for :customers, controllers: {
      sessions:      'customers/sessions',
      passwords:     'customers/passwords',
      registrations: 'customers/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routiSZng.html

  namespace :admins do
    resources :orders, only: [:index,:show,:update]
    get '/top', to: "orders#top"
    resources :customers
    resources :products
    resources :genres, only: [:index ,:create, :edit, :update]
    get 'product/top',to: "products#top"

  end
  namespace :customers do
    get '/thanks', to: 'orders#thanks'
    resources :carts, only: [:index ,:create, :update, :destroy]
    delete '/all_carts_destroy', to: "carts#all_destroy", as: "all_destroy"
    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        post :new,path: :new, as: :new
        post :about
      end
    end
  end
  resources :products

    get '/customer/cancel', to: 'customers#cancel'
    get '/customers', to: 'customers#show'
    get '/customers/pass', to: 'customers#pass'
    resources :customers do
      patch :customer_status
      resources :deliveries, only:[:index, :edit, :update, :destroy, :new, :create]
  end
  devise_scope :customer do
    get '/customers/sign_out' => 'devise/sessions#destroy'
  end

end

app/models/order.rb
class Order < ApplicationRecord
	has_many :order_details
	accepts_nested_attributes_for :order_details
	belongs_to :customer
	enum order_status:{
	入金待ち: 0, 入金確認: 1, made: 2, 発送準備中: 3, 発送済み: 4
	}
	enum payment_method:{
	クレジットカード: 0, 現金振込: 1
	}
end

app/controllers/admins/orders_controller.rb
class Admins::OrdersController < ApplicationController
	def index
		@orders = Order.all
	end
	def update
		@order = Order.find(params[:id])
		@order_details = @order.order_details
        # @order.update(order_params)
        @order.update(order_status: params[:order][:order_status].to_i)
	        if @order_details.where(production_status: 2).any?
	        	  @order.update(order_status: 2)
	        else
	        end
	        if @order.order_status_before_type_cast == 1
	        	@order_details.each do |item|
	           		item.update(production_status: 1)
	       		end
	        end
	        if @order_details.count == @order_details.where(production_status: 3).count
	        	  @order.update(order_status: 3)
	        else
	        end

        redirect_to admins_order_path
	end
	def show
		@order = Order.find(params[:id])
	end
	def top
		from = Time.current.beginning_of_day
		to = Time.current.end_of_day
		@count = Order.where(created_at: from..to).count

	end
	def order_params
		params.permit(:deliver_to, :shipping_name, :order_postshipping_cost, :order_status, :payment_method, :created_at, order_detail_attributes: [:id, :production_status])
	end
	def order_detail_params
		params.require(:order_detail).permit(:ordered_price, :ordered_item_name, :ordered_item_count, :production_status)
	end
end

app/controllers/customers/orders_controller.rb
class Customers::OrdersController < ApplicationController
	# before_action :order_params
	def index
		@orders = current_customer.orders.includes(:order_details)
	end
	def show
		@order = Order.find(params[:id])
	end
	def about
		@customer = current_customer
		@order = @customer.orders.new
		@carts = current_customer.carts
	    @tax = Tax.find(2).tax
	    @products = Product.all
	    @total_price = 0
	    @carts.each do |cart|
     	@total_price += cart.product.non_tax * cart.item_count * 1.1
     	end
		if params[:post] == "post_mine_group"
			@order.order_post = @customer.postal_code
			@order.deliver_to = @customer.address
			@order.shipping_name = @customer.lastname + @customer.firstname
		elsif params[:post] == "post_deli_group"
			delivery = Delivery.find(params[:registered_address_id].to_i)
  			@order.order_post = delivery.delivery_post
			@order.deliver_to = delivery.delivery_address
			@order.shipping_name = delivery.delivery_name
	  	elsif
	  		params[:post] == "post_new_group"
	  		@order.order_post = params[:order_post]
	  		@order.deliver_to = params[:deliver_to]
	  		@order.shipping_name = params[:shipping_name]
		end
    end
	def thanks
		@customer = current_customer
	end
	def new
		@customer = current_customer
		@deliveries = current_customer.deliveries
	end
	def create
        @order = current_customer.orders.new(order_params)
		if @order.save
		   current_customer.carts.each do |cart|
				@order_detail = OrderDetail.new
				@order_detail.order_id = @order.id
				@order_detail.ordered_item_name = cart.product.product_name
				@order_detail.ordered_price = params[:ordered_price]
				@order_detail.ordered_item_count = cart.item_count
				@order_detail.save
				current_customer.carts.delete_all
		   end
		    redirect_to customers_thanks_path
   		else
      		render :new
    	end
	end


private

	def order_params
		params.permit(:deliver_to, :shipping_name, :order_post)
	end
	def order_detail_params
		params.require(:order_detail).permit(:ordered_price, :ordered_item_name)
	end
end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admins/orders/index.html.erb
<body>
<%= render 'headfoot/header' %>
<div class="container">
	<div class="row">
		<h3>注文一覧画面</h3>
	</div>
	<div class="col-xs-1"></div>
	<div class="row col-xs-10">
		<table class="col-lg-8 table">
			<tr>
				<th class="col-lg-2">購入日時</th>
				<th class="col-lg-2">購入者</th>
				<th class="col-lg-2">注文個数</th>
				<th class="col-lg-2">注文ステータス</th>
			</tr>
				<% @orders.each do |order| %>
			<tr class="admin-order-index">
				<td class="admin-order-index">
					<%= link_to admins_order_path(order.id) do %>
					<%= order.created_at.strftime('%Y/%m/%d %H:%M:%S') %>
					<% end %>
				</td>
				<td class="admin-order-index">
					<%= order.customer.lastname %>
					<%= order.customer.firstname %>
				</td>
				<td class="admin-order-index">
					<% sum = 0 %>
					<% order.order_details.each do |detail| %>
		            <% sum += detail.ordered_item_count.to_i %>
		            <% end %>
		            <%= sum %>
				</td>
				<td class="admin-order-index">
					<%= order.order_status %>
				</td>
			</tr>
			    <% end %>
	    </table>
	</div>
</div>
<%= render 'headfoot/footer' %>
</body>

app/views/admins/orders/show.html.erb
<body>
<%= render 'headfoot/header' %>
<body>
<div class="container">
<!-- 購入者関連 -->
	<div class="row col-lg-12">
		<div class="col-xs-5">
			<h4>注文詳細画面</h4>
			<table class="admin-order-customer">
				<tr class="admin-order-show">
					<th class="col-xs-3">購入者</th>
					<td class="col-xs-8">
						<%= link_to admins_customer_path(@order.customer) do %>
						<%= @order.customer.lastname %>
						<%= @order.customer.firstname %>
						<% end %>
					</td>
				</tr>
				<tr class="admin-order-show">
					<th class="col-xs-3">配送先</th>
					<td class="col-xs-8">
					  〒<%= @order.order_post %>
						<%= @order.deliver_to %><br>
						<%= @order.shipping_name %>
					</td>
				</tr>
				<tr class="admin-order-show">
					<th class="col-xs-3">支払方法</th>
					<td class="col-xs-8">
						<%= @order.payment_method %>
					</td>
				</tr>
				<tr class="admin-order-show">
					<th class="col-xs-3">ステータス</th>
					<td class="col-xs-8">
						<%= form_for(@order, url:{controller: 'orders', action: 'update'}) do |f| %>
						<%= f.select :order_status, [['入金待ち', 0],['入金確認', 1], ['製作中', 2],['発送準備中', 3],['発送済み', 4]], { selected: @order.order_status_before_type_cast } %>
						</td>
				</tr>
			</table>
		</div>
	</div>
	<div class="sukima"></div>
<!-- 商品関連 -->
	<div class="row">
		<div class="col-lg-8 order-item">
			<div class="col-lg-12">
				<table class="table col-xs-10 ">
						<tr class="order-show">
							<th>商品名</th>
							<th>単価（税込）</th>
							<th>数量</th>
							<th>小計</th>
							<th>製作ステータス</th>
						</tr>
						<% @order.order_details.each do |order| %>
						<tr class="order-show">
							<td class="col-xs-2">
								<%= order.ordered_item_name %>
							</td>
							<td class="col-xs-1">
								<%= order.ordered_price %>
							</td>
							<td class="col-xs-1">
								<%= order.ordered_item_count %>
							</td>
							<td class="col-xs-1">
								<%= order.ordered_item_count.to_i * order.ordered_price.to_i %>
							</td>
							<td class="col-xs-1">
	  							<%= f.fields_for :order_detail do |i| %>
								<%= i.select :production_status, [['着手不可', 0],['製作待ち', 1], ['製作中', 2],['製作完了', 3]], { selected: @order.order_status_before_type_cast } %>
							<% end %>
						<% end %>
							</td>
						</tr>
				</table>
			</div>
		</div>
		<%= f.submit "更新", class: "btn btn-primary reload-btn" %>
		<% end %>
	<!-- 支払関係 -->
		<div class="col-xs-4">
			<table class="pay-table-show">
				<tr class="order-show">
					<th class="col-xs-2">商品合計</th>
					<td class="col-xs-2">
						<% sum = 0 %>
			            <% @order.order_details.each do |order| %>
			            <% sub_total = order.ordered_price.to_i * order.ordered_item_count.to_i %>
			            <% sum += sub_total %>
			            <% end %>
			            <%= sum %>円
					</td>
				</tr>
				<tr class="order-show">
					<th class="col-xs-2">送料</th>
					<td class="col-xs-2">
						<%= @order.shipping_cost %>円
					</td>
				</tr>
				<tr class="order-show">
					<th class="col-xs-2">請求合計金額</th>
					<td class="col-xs-2">
			            <% @order.order_details.each do |order| %>
			            <% order.ordered_price.to_i * order.ordered_item_count.to_i %>
			            <% end %>
			            <% sum %>
						<%= sum + @order.shipping_cost %>円
					</td>
				</tr>
			</table>
		</div>
	</div>
</div>
<%= render 'headfoot/footer' %>
</body>

app/views/admins/orders/top.html.erb
<body>

<%= render 'headfoot/header' %>
<div class="container">
	<h2>　　管理者画面</h2>
	<div class="row">
		<h2>　　　本日の注文件数
		<%= link_to admins_orders_path do %>
		 <%= @count %>
		<% end %>
		   件 </h2>
	</div>
</div>
<%= render 'headfoot/footer' %>

</body>